Tracker:AddLocations("locations/Animal Antics.json")
Tracker:AddLocations("locations/Arctic Abyss.json")
Tracker:AddLocations("locations/Barrel Bayou.json")
Tracker:AddLocations("locations/Black Ice Battle.json")
Tracker:AddLocations("locations/Bramble Blast.json")
Tracker:AddLocations("locations/Bramble Scramble.json")
Tracker:AddLocations("locations/Castle Crush.json")
Tracker:AddLocations("locations/Chain Link Chamber.json")
Tracker:AddLocations("locations/Clapper's Cavern.json")
Tracker:AddLocations("locations/Fiery Furnace.json")
Tracker:AddLocations("locations/Gangplank Galley.json")
Tracker:AddLocations("locations/Ghostly Grove.json")
Tracker:AddLocations("locations/Glimmer's Galleon.json")
Tracker:AddLocations("locations/Gusty Glade.json")
Tracker:AddLocations("locations/Haunted Hall.json")
Tracker:AddLocations("locations/Hornet Hole.json")
Tracker:AddLocations("locations/Hot-Head Hop.json")
Tracker:AddLocations("locations/Jungle Jinx.json")
Tracker:AddLocations("locations/Kannon's Klaim.json")
Tracker:AddLocations("locations/King Zing Sting.json")
Tracker:AddLocations("locations/Kleever's Kiln.json")
Tracker:AddLocations("locations/Klobber Karnage.json")
Tracker:AddLocations("locations/Kreepy Krow.json")
Tracker:AddLocations("locations/Krockhead Klamber.json")
Tracker:AddLocations("locations/Krow's Nest.json")
Tracker:AddLocations("locations/Kudgel's Kontest.json")
Tracker:AddLocations("locations/Lava Lagoon.json")
Tracker:AddLocations("locations/Lockjaw's Locker.json")
Tracker:AddLocations("locations/Mainbrace Mayhem.json")
Tracker:AddLocations("locations/Mudhole Marsh.json")
Tracker:AddLocations("locations/Parrot Chute Panic.json")
Tracker:AddLocations("locations/Pirate Panic.json")
Tracker:AddLocations("locations/Rambi Rumble.json")
Tracker:AddLocations("locations/Rattle Battle.json")
Tracker:AddLocations("locations/Red-Hot Ride.json")
Tracker:AddLocations("locations/Rickety Race.json")
Tracker:AddLocations("locations/Screech's Sprint.json")
Tracker:AddLocations("locations/Slime Climb.json")
Tracker:AddLocations("locations/Squawks's Shaft.json")
Tracker:AddLocations("locations/Stronghold Showdown.json")
Tracker:AddLocations("locations/Target Terror.json")
Tracker:AddLocations("locations/Topsail Trouble.json")
Tracker:AddLocations("locations/Toxic Tower.json")
Tracker:AddLocations("locations/Web Woods.json")
Tracker:AddLocations("locations/Windy Well.json")
Tracker:AddLocations("locations/Overworld.json")
